### ISSUE TITLE
Cannot be restored when the variable value is Superglobals

### ISSUE THREAD

**Issue by L2ksy0d** [simon816/PHPDeobfuscator#15]
sample:
```php
<?php
    $a = $_POST['a'];
    $b = $_GET['b'];
    $c = 'assert';
    $a($b);
    $c($a);
    echo "aaa";
```
it doesn't seem to get a value, and it appears empty.

**Comment by simon816** [comment]
What is it that is wrong?

I get this, which looks correct:
```
<?php

$a = $_POST['a'];
$b = $_GET['b'];
$c = 'assert';
$a($b);
assert($a);
echo "aaa";
```

**Comment by L2ksy0d** [comment]
Oh, I mean can the value of $a be restored, because it's the special variable "Superglobals".
Just like `$c($a)` is restored to `assert($_POST['a'])`.

**Comment by simon816** [comment]
Okay, so in a simple example like:
```php
$a = ...
$b = $a;
echo $b;
```
Then `echo $b` can be replaced by `echo $a`?

This won't work in general, as copies are done by-value, which is fine for scalar values but not for arrays.
I don't think superglobals will be any different here.

In an example such as:
```php
$a = [1, 2, 3];
$b = $a;
array_pop($b);
```
You can't replace `array_pop($b)` with `array_pop($a)` because they are different arrays. `array_pop($b)` only affects array `$b`, not array `$a`.

I've also just realised that it's unsound to assume `$c` is always "assert" when they are global variables. e.g. consider:

```php
function change_globals() {
    global $c;
    $c = 'foo';
}

$a = $_POST['a'];
$b = $_GET['b'];
$c = 'assert';
$a($b);
$c($a);
echo "aaa";
```
If `$_POST['a']` was the string "change_globals", then suddenly `$c` is no longer "assert" but is instead "foo".

**Comment by L2ksy0d** [comment]
tks for your answer.
