### ISSUE TITLE
Not correct decode

### ISSUE THREAD

**Issue by Vladzimir** [simon816/PHPDeobfuscator#2]
Not correct decode goto and multi label.
                        lab1:
                        lab2:
                        lab3:

**Comment by simon816** [comment]
Hi, it is unclear what the problem is from your description. Could you share a snippet of code that doesn't deobfuscate well?

**Comment by Vladzimir** [comment]
encode file https://pastebin.com/FCiBc6Yc
decode file https://pastebin.com/egh6SW8s

**Comment by simon816** [comment]
I see. The obfuscation in that file appears to rewrite if/else into ifs and gotos.
I'll see if I can convert them back to if/else. Hopefully the code is more readable so you can manually follow the control flow.

The reason why DIR_SYSTEM is being concatenated to the string is because it's emulating PHP's behaviour where undefined constants become the string value of it's name.
example:
```php
<?php

echo "VALUE: " . DIR_SYSTEM;
```

Demo: https://3v4l.org/trpHp
```
Warning: Use of undefined constant DIR_SYSTEM - assumed 'DIR_SYSTEM' (this will throw an Error in a future version of PHP) in /in/trpHp on line 3
VALUE: DIR_SYSTEM
```

If you define the constant, it will concatenate it, e.g:

```php
<?php

define('DIR_SYSTEM', '/');

echo DIR_SYSTEM . "library/adw/autofield.php";
```
Becomes:
```php
<?php

define('DIR_SYSTEM', '/');
echo "/library/adw/autofield.php";
```

**Comment by Vladzimir** [comment]
Thanks for answers.
